# Generated by Django 5.0.4 on 2026-04-23 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_block', models.DecimalField(decimal_places=2, max_digits=10)),
                ('strength_rating', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='blocks/')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('LOADING', 'Loading'), ('TRANSIT', 'On Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.blocktype')),
                ('delivery_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blocks.deliveryzone')),
            ],
        ),
    ]
